# Generated by Django 3.2.9 on 2021-11-10 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='id_num',
            field=models.CharField(blank=True, default='000000000000', max_length=15, null=True, verbose_name='ИИН'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='full_name',
            field=models.CharField(blank=True, max_length=250, null=True, unique=True, verbose_name='Организация'),
        ),
    ]
