# Generated by Django 3.2.9 on 2021-11-10 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20211110_1418'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loglist',
            name='doc_date',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='vacations',
            name='doc_date',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Дата создания'),
        ),
    ]
