# Generated by Django 3.2.9 on 2021-11-12 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_customuser_available_vacations'),
    ]

    operations = [
        migrations.AddField(
            model_name='loglist',
            name='doc_id_1c',
            field=models.CharField(default='', max_length=250, verbose_name='Идентификатор документа 1С'),
        ),
        migrations.AddField(
            model_name='loglist',
            name='doc_id_py',
            field=models.CharField(default='', max_length=250, verbose_name='Идентификатор документа'),
        ),
        migrations.AddField(
            model_name='vacations',
            name='days_used',
            field=models.IntegerField(default=0, verbose_name='Выбранное количество дней отпуска'),
        ),
        migrations.AddField(
            model_name='vacations',
            name='doc_id_1c',
            field=models.CharField(default='', max_length=250, verbose_name='Идентификатор документа 1С'),
        ),
        migrations.AddField(
            model_name='vacations',
            name='doc_id_py',
            field=models.CharField(default='', max_length=250, verbose_name='Идентификатор документа'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='available_vacations',
            field=models.IntegerField(blank=True, default=0, verbose_name='Доступные дни отпуска'),
        ),
    ]
