# Generated by Django 3.2.9 on 2021-11-12 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20211112_1151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacations',
            name='days_used',
            field=models.IntegerField(default=0, verbose_name='Количество дней отпуска'),
        ),
    ]
