# Generated by Django 3.2.9 on 2021-11-16 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_vacations_days_used'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vacations',
            name='days_used',
        ),
        migrations.AddField(
            model_name='customuser',
            name='phone',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Телефон'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='third_name',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Отчество'),
        ),
    ]
