# Generated by Django 3.2.9 on 2021-11-16 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_auto_20211116_1608'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='available_vacations',
        ),
    ]
