# Generated by Django 3.2.9 on 2021-11-16 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_remove_customuser_available_vacations'),
    ]

    operations = [
        migrations.AddField(
            model_name='loglist',
            name='doc_id_1cDoc',
            field=models.CharField(default='', max_length=250, verbose_name='Идентификатор документа 1С.Документооборот'),
        ),
        migrations.AddField(
            model_name='vacations',
            name='doc_id_1cDoc',
            field=models.CharField(default='', max_length=250, verbose_name='Идентификатор документа 1С.Документооборот'),
        ),
    ]
