# Generated by Django 3.2.9 on 2021-11-17 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_auto_20211116_1624'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacations',
            name='id',
            field=models.IntegerField(editable=False, primary_key=True, serialize=False),
        ),
    ]
