# Generated by Django 3.2.9 on 2021-11-17 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_alter_vacations_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loglist',
            name='id',
            field=models.IntegerField(editable=False, primary_key=True, serialize=False),
        ),
    ]
