# Generated by Django 3.2.9 on 2021-11-17 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_alter_loglist_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacations',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
