# Generated by Django 3.2.9 on 2021-11-17 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_alter_vacations_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loglist',
            name='id',
            field=models.CharField(max_length=250, primary_key=True, serialize=False, unique=True),
        ),
    ]
