# Generated by Django 3.2.9 on 2021-11-17 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_alter_loglist_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loglist',
            name='doc_id_1c',
        ),
        migrations.RemoveField(
            model_name='loglist',
            name='doc_id_1cDoc',
        ),
        migrations.RemoveField(
            model_name='loglist',
            name='doc_id_py',
        ),
        migrations.RemoveField(
            model_name='vacations',
            name='doc_id_1c',
        ),
        migrations.RemoveField(
            model_name='vacations',
            name='doc_id_1cDoc',
        ),
        migrations.RemoveField(
            model_name='vacations',
            name='doc_id_py',
        ),
    ]
