# Generated by Django 3.2.9 on 2021-11-19 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_auto_20211117_1141'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacations',
            name='vacation_type',
            field=models.IntegerField(default=0, verbose_name='Тип отпуска'),
        ),
    ]
