# Generated by Django 3.2.9 on 2021-11-26 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_vacations_vacation_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='full_name',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Организация'),
        ),
        migrations.AlterField(
            model_name='vacations',
            name='vacation_type',
            field=models.CharField(max_length=250, verbose_name='Тип отпуска'),
        ),
    ]
