# Generated by Django 3.2.9 on 2021-11-30 10:04

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0022_auto_20211126_1452'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loglist',
            name='id_user',
            field=models.UUIDField(default=uuid.uuid4, verbose_name='Идентификатор пользователя'),
        ),
    ]
