# Generated by Django 3.2.9 on 2021-12-15 11:47

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0023_alter_loglist_id_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='MawsEditStatus',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('id_user', models.UUIDField(default=uuid.uuid4, verbose_name='Идентификатор пользователя')),
                ('user', models.CharField(max_length=250, verbose_name='Пользователь')),
                ('storage', models.CharField(max_length=250, verbose_name='Склад')),
                ('placement', models.CharField(max_length=250, verbose_name='Помещение')),
                ('status', models.BooleanField(default=False, verbose_name='Статус помещения')),
            ],
            options={
                'verbose_name': 'Статусы помещений',
                'verbose_name_plural': 'Статусы помещений',
            },
        ),
    ]
