# Generated by Django 3.2.9 on 2021-12-15 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0024_mawseditstatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mawseditstatus',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False, unique=True),
        ),
    ]
