# Generated by Django 3.2.9 on 2021-12-20 04:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0025_alter_mawseditstatus_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mawseditstatus',
            name='status',
        ),
    ]
