# Generated by Django 3.2.9 on 2021-12-21 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0026_remove_mawseditstatus_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mawseditstatus',
            name='id',
            field=models.IntegerField(editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
