# Generated by Django 3.2.9 on 2021-12-28 12:15

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0027_alter_mawseditstatus_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormsMaws',
            fields=[
                ('id', models.IntegerField(editable=False, primary_key=True, serialize=False, unique=True)),
                ('id_user', models.UUIDField(default=uuid.uuid4, verbose_name='Идентификатор пользователя')),
                ('name', models.CharField(max_length=250, verbose_name='Название')),
                ('itemCode', models.CharField(max_length=250, verbose_name='Код')),
                ('itemName', models.CharField(max_length=250, verbose_name='Наименование')),
                ('measure', models.CharField(max_length=250, verbose_name='Ед.изм')),
                ('inStock', models.CharField(max_length=250, verbose_name='Остаток')),
                ('writeoff', models.CharField(max_length=250, verbose_name='Списание')),
            ],
            options={
                'verbose_name': 'Списание МАФС',
                'verbose_name_plural': 'Списание МАФС',
            },
        ),
    ]
