# Generated by Django 3.2.9 on 2021-12-28 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0028_formsmaws'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formsmaws',
            name='inStock',
        ),
        migrations.RemoveField(
            model_name='formsmaws',
            name='itemCode',
        ),
        migrations.RemoveField(
            model_name='formsmaws',
            name='itemName',
        ),
        migrations.RemoveField(
            model_name='formsmaws',
            name='measure',
        ),
        migrations.RemoveField(
            model_name='formsmaws',
            name='writeoff',
        ),
        migrations.AddField(
            model_name='formsmaws',
            name='goods',
            field=models.TextField(default='', verbose_name='goods JSON'),
        ),
    ]
