# Generated by Django 3.2.9 on 2021-12-28 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0029_auto_20211228_1757'),
    ]

    operations = [
        migrations.AddField(
            model_name='formsmaws',
            name='responsibles',
            field=models.TextField(default='', verbose_name='responsibles JSON'),
        ),
    ]
