# Generated by Django 3.2.9 on 2021-12-29 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0030_formsmaws_responsibles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formsmaws',
            name='name',
            field=models.TextField(default='', verbose_name='Название'),
        ),
    ]
