# Generated by Django 3.2.9 on 2022-01-11 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0031_alter_formsmaws_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='f_enter',
            field=models.BooleanField(blank=True, default=True, verbose_name='New user'),
        ),
    ]
