# Generated by Django 3.2.9 on 2022-01-12 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0032_customuser_f_enter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='f_enter',
        ),
    ]
