# Generated by Django 3.2.9 on 2022-01-12 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0033_remove_customuser_f_enter'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='one_off',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Одноразовый пароль'),
        ),
    ]
