# Generated by Django 3.2.9 on 2022-01-21 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0034_customuser_one_off'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='email_corp',
            field=models.EmailField(blank=True, default='', max_length=254, null=True, verbose_name='Корпоративная почта'),
        ),
    ]
