# Generated by Django 3.2.9 on 2022-01-25 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0035_customuser_email_corp'),
    ]

    operations = [
        migrations.AddField(
            model_name='loglist',
            name='line_manager',
            field=models.CharField(default='', max_length=250, verbose_name='Line Manager'),
        ),
        migrations.AddField(
            model_name='vacations',
            name='line_manager',
            field=models.CharField(default='', max_length=250, verbose_name='Line Manager'),
        ),
    ]
