# Generated by Django 3.2.9 on 2022-02-01 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0036_auto_20220125_1607'),
    ]

    operations = [
        migrations.AddField(
            model_name='loglist',
            name='tag',
            field=models.CharField(default='', max_length=250, verbose_name='tag'),
        ),
    ]
