# Generated by Django 3.2.9 on 2022-02-01 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0037_loglist_tag'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='formsmaws',
            options={'verbose_name': 'Черновики МАФС', 'verbose_name_plural': 'Черновики МАФС'},
        ),
        migrations.AddField(
            model_name='formsmaws',
            name='date',
            field=models.CharField(default='', max_length=250, verbose_name='Дата'),
        ),
        migrations.AddField(
            model_name='formsmaws',
            name='location',
            field=models.CharField(default='', max_length=250, verbose_name='Локация'),
        ),
        migrations.AddField(
            model_name='formsmaws',
            name='manager',
            field=models.CharField(default='', max_length=250, verbose_name='Менеджер склада'),
        ),
        migrations.AddField(
            model_name='formsmaws',
            name='placement',
            field=models.CharField(default='', max_length=250, verbose_name='Помещение'),
        ),
        migrations.AddField(
            model_name='formsmaws',
            name='storage',
            field=models.CharField(default='', max_length=250, verbose_name='Склад'),
        ),
    ]
