# Generated by Django 3.2.9 on 2022-02-02 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0039_alter_loglist_line_manager'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loglist',
            name='line_manager',
            field=models.CharField(default='', max_length=250, verbose_name='Line Manager'),
        ),
    ]
