# Generated by Django 3.2.9 on 2022-02-02 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0040_alter_loglist_line_manager'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loglist',
            name='line_manager',
        ),
        migrations.AddField(
            model_name='loglist',
            name='description',
            field=models.CharField(default='', max_length=250, verbose_name='Описание/Номер'),
        ),
    ]
