# Generated by Django 3.2.9 on 2022-02-02 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0041_auto_20220202_0950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loglist',
            name='doc_date',
            field=models.DateTimeField(null=True, verbose_name='Дата создания'),
        ),
    ]
