# Generated by Django 3.2.9 on 2022-02-02 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0044_auto_20220202_1022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loglist',
            name='description',
            field=models.CharField(default='', max_length=250, null=True, verbose_name='Описание/Номер'),
        ),
    ]
