# Generated by Django 3.2.9 on 2022-02-09 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0046_alter_formsmaws_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loglist',
            name='full_name',
        ),
        migrations.RemoveField(
            model_name='vacations',
            name='full_name',
        ),
    ]
