# Generated by Django 3.2.9 on 2022-03-04 13:15

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0054_alter_editphone_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='editphone',
            name='id_num',
            field=models.CharField(default='', max_length=15, verbose_name='ИИН'),
        ),
        migrations.AlterField(
            model_name='editphone',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True),
        ),
    ]
